projects:
  phonestock:
    schemaPath: src/graphql/schema.json
    includes:
      - src/shared/services/phone.service.aws.ts
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: src/API.ts
        docsFilePath: src/shared/services
